export const GET_DOGS = "GET_DOGS"
export const GET_DOG = "GET_DOG"
export const DOG_DETAIL = "DOG_DETAIL"
export const FILTER = "FILTER"
export const ORDER = "ORDER"
export const ORDER_WEIGHT = "ORDER_WEIGHT"
export const SET_PAGE = "SET_PAGE"
export const DOGS_CURRENT_PAGE = "DOGS_CURRENT_PAGE"